repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.3
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-bugbear]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: Python style guide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "1.5.3" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: "(^docs/conf.py)|(^src/windeval/app.py)"
